Add ability to enable/disable stdout/file logging
PretendoNetwork/plogger-go pull request #3
Opened 2023-09-01 12:00 UTC by PabloMK7

Adds the ability to enable or disable file or stdout logging. In this implementation the files are still created, which allows enabling file logging at any point.

2023-09-02 02:44 UTC, jonbarrow commented
Multiple loggers may exist at one time, so it would make more sense to keep these kinds of configuration details per-logger instance. It was fine the way it was before with keeping these on the struct, there just needs to be some way to update them. Either by exporting the variables or providing setter methods on the struct (something like `SetLogToFile(false)`). We typically use getter/setter methods in our libraries, so that would be preferred, but it's not the end of the world

2024-04-19 17:16 UTC, PabloMK7 commented
Applied suggestions, sorry for the (long) delay, I know how to code in Go now x)

2024-07-03 12:00 UTC, DaniElectra reviewed
I have also noticed that none of the functions on here have godoc comments, but I'm not sure if that should be resolved on this PR

2025-02-05 19:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PretendoNetwork/plogger-go?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PretendoNetwork/plogger-go?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PretendoNetwork/plogger-go?pullRequest=3) it.</sub>

2025-02-16 08:37 UTC, binaryoverload requested changes
Could this have a way to disable logging to file via an env var please? That will allow us in infra to just have LOGGING=false to stop the local log files being created

2025-02-16 08:44 UTC, PabloMK7 commented
Hello, I don't have plans to come back to this commit in the near future. At this point I think it's better for someone else to pick up on it if this functionality is needed. ^^'

2025-02-16 08:46 UTC, binaryoverload commented
> Hello, I don't have plans to come back to this commit in the near future. At this point I think it's better for someone else to pick up on it if this functionality is needed. ^^'
> 
> If someone can, then I will close the PR so it can be added in another one.

No problem! Jon has picked this up - please leave this PR open as Jon can edit it, and we'll merge without needing anything else from you 🙂

2025-02-16 17:04 UTC, jonbarrow commented
> Could this have a way to disable logging to file via an env var please? That will allow us in infra to just have something like `LOGGING=false` to stop the local log files being created

Is there any specific implementation/design you had in mind for this? We can't really have this work on a per-logger basis since multiple loggers *can* exist at one time with their own settings. We could have it set for the global option? But for most of our use cases this sounds like it would be something better done on the consumer side, not here (IE, the servers are the ones with the env vars that disable logging)

2025-02-16 17:11 UTC, binaryoverload commented
@jonbarrow I think a global environment option would work well - something like `PLOGGER_LOG_TO_FILE`

I would normally agree that it would be implemented on the consumer side, but since this library is essentially internal and all servers would just have the exact same implementation from getting the env var, I think doing it globally at the library level works well.

Means that we don't need to have yet another piece of code duplicated across the many game servers, and having the functionality just requires an update

2025-02-16 17:35 UTC, jonbarrow commented
> @jonbarrow I think a global environment option would work well - something like `PLOGGER_LOG_TO_FILE`
> 
> I would normally agree that it would be implemented on the consumer side, but since this library is essentially internal and all servers would just have the exact same implementation from getting the env var, I think doing it globally at the library level works well.
> 
> Means that we don't need to have yet another piece of code duplicated across the many game servers, and having the functionality just requires an update

Since everything is enabled by default, and the env vars would only serve to disable logging, I've named them as such. Also added a proper README with API docs

2025-02-16 19:09 UTC, binaryoverload approved these changes
Looks good!

2025-02-16 19:19 UTC, merged